### ISSUE TITLE
Docked Dev Tools

### ISSUE THREAD

**Issue by ambethia** [jhen0409/hyperterm-open-devtools#3]
It would be great if it were possible to dock the dev tools for the displayed webpage directly to the HyperTerm window. Is this possible? I image this might be similar to the issue that prevents the [Vivaldi](http://vivaldi.com) Browser's dev tools from being docked to the window, but I figured I'd ask, or at least start the conversation.

**Comment by jhen0409** [comment]
Unfortunately, currently it's not possible, see https://github.com/electron/electron/issues/3177.
